name = "BetaVQE"
uuid = "11c46944-b2ae-4555-bf56-5433fb292ea1"
authors = ["Jin-Guo Liu <cacate0129@iphy.ac.cn>", "Lei Wang <wangleiphy@gmail.com>"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ChainRulesCore = "1"
Comonicon = "0.12"
JLD2 = "0.4"
Optimisers = "0.2"
StatsBase = "0.33"
Yao = "0.8"
Zygote = "0.6"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
